version: '3.8'

services:
  # Backend Service (API + MCP servers)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cramwell-backend
    ports:
      - "${API_PORT:-8001}:8001"  # API server
      - "${MCP_PORT:-8000}:8000"  # MCP server
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8001
      - MCP_PORT=8000
      - MCP_TRANSPORT=${MCP_TRANSPORT:-streamable-http}
      - FRONTEND_URL=https://cramwell.vercel.app
      - FRONTEND_URL_DEV=http://localhost:3000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
    volumes:
      - ./backend/src:/app/src
      - ./backend/prompts:/app/prompts
      - ./backend/uploads:/app/uploads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - cramwell-network

networks:
  cramwell-network:
    driver: bridge

volumes:
  uploads:
    driver: local 