version: '3.8'

services:
  # MCP Server
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cramwell-mcp
    ports:
      - "${MCP_PORT:-8000}:8000"
    environment:
      - MCP_PORT=8000
      - MCP_TRANSPORT=${MCP_TRANSPORT:-streamable-http}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
    volumes:
      - ./src:/app/src
      - ./prompts:/app/prompts
    command: ["uv", "run", "python", "-m", "src.cramwell.server"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - cramwell-network

  # API Server
  api-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cramwell-api
    ports:
      - "${API_PORT:-8001}:8001"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8001
      - MCP_URL=http://mcp-server:8000/mcp
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
    volumes:
      - ./src:/app/src
      - ./uploads:/app/uploads
    command: ["uvicorn", "src.cramwell.api_server:app", "--host", "0.0.0.0", "--port", "8001"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    depends_on:
      mcp-server:
        condition: service_healthy
    networks:
      - cramwell-network

  # Frontend (Next.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cramwell-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - NEXT_PUBLIC_API_URL=http://api-server:8001
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    depends_on:
      api-server:
        condition: service_healthy
    networks:
      - cramwell-network

networks:
  cramwell-network:
    driver: bridge

volumes:
  uploads:
    driver: local 